FROM registry.access.redhat.com/ubi8:8.5

ENV SBO_REPO https://github.com/redhat-developer/service-binding-operator
ENV SBO_REPO_COMMIT master

ENV SBO_DIR /tmp/sbo.git
ENV KUBECONFIG_DIR /tmp
ENV KUBECONFIG ${KUBECONFIG_DIR}/kubeconfig

RUN yum -y --nodocs install git python3 jq python3-pip && \
    yum clean all
RUN pip3 install --upgrade pip
RUN pip3 --no-cache-dir install --upgrade awscli
RUN yum clean all
RUN curl -SL -o oc.tar.gz https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/ocp/latest/openshift-client-linux.tar.gz && \
    tar -xvf oc.tar.gz && \
    chmod +x oc && \
    chmod +x kubectl && \
    mv -vf oc /usr/bin/oc && \
    mv -vf kubectl /usr/bin/kubectl && \
    rm -rf oc.tar.gz

WORKDIR ${SBO_DIR}

ENV PWD ${SBO_DIR}

COPY test-entrypoint.sh /test-entrypoint.sh

ENTRYPOINT [ "/test-entrypoint.sh" ]