---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: service-binding-leader-election-rolebinding
  namespace: service-binding-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: service-binding-leader-election-role
subjects:
- kind: ServiceAccount
  name: service-binding-operator
  namespace: service-binding-operator