---
apiVersion: v1
kind: Service
metadata:
  name: service-binding-webhook-service
  namespace: {{.Release.Namespace}}
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 9443
  selector:
    control-plane: service-binding-controller-manager