---
apiVersion: v1
kind: Service
metadata:
  name: service-binding-webhook-service
  namespace: service-binding-operator
  labels:
    app.kubernetes.io/managed-by: Helm
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 9443
  selector:
    control-plane: service-binding-controller-manager